name: Docker Deploy CI/CD
run-name: Deploy to Docker Hub
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Generate Environment File
        run: |
          echo "NEXT_PUBLIC_CLIENT=${{ secrets.NEXT_PUBLIC_CLIENT }}" >> .env.production

      - name: Build and Push Docker Image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME}}/along:latest .
          docker push ${{ secrets.DOCKERHUB_USERNAME}}/along:latest

      - name: Deploy to Server with Docker Compose
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SERVER_PORT }}
          script: |
            cd /home/${{ secrets.SERVER_USER }}

            if [ ! -d  "along/.git" ]; then
              echo "Repository does not exist. Cloning the repository..."
              git clone https://github.com/${{ github.repository }}.git along
              cd along
              git checkout main
            else
              echo "Repository exists. Pulling latest changes..."
              cd along
              git pull origin main
            fi

            if ! docker network inspect shared_network >/dev/null 2>&1; then
              echo "Network 'shared_network' does not exist. Creating it..."
              docker network create shared_network
            fi

            docker-compose pull
            docker-compose down
            docker image prune -af
            docker-compose up -d
